apiVersion: v1
kind: Secret
metadata:
  name: ogivc
data:
  GOOGLE_CLIENT_SECRET: {{ .Values.GOOGLE_CLIENT_SECRET | b64enc }} 
  GOOGLE_ID: {{ .Values.GOOGLE_ID | b64enc }}
  MONGODB_URI: {{ .Values.MONGODB_URI | b64enc }}
  NEXTAUTH_SECRET: {{ .Values.NEXTAUTH_SECRET | b64enc }}
type: Opaque
