apiVersion: v1
kind: Service
metadata:
  labels:
    app: ogivc
  name: ogivc
spec:
  ports:
  - port: 3300
    protocol: TCP
    targetPort: 3300
  selector:
    app: ogivc
  type: NodePort
status:
  loadBalancer: {}
